using System;

namespace ImGui;

public struct ImGuiStyle
{
    public float FontSizeBase;
    public float FontScaleMain;
    public float FontScaleDpi;

    public float Alpha;
    public float DisabledAlpha;
    public ImVec2 WindowPadding;
    public float WindowRounding;
    public float WindowBorderSize;
    public float WindowBorderHoverPadding;
    public ImVec2 WindowMinSize;
    public ImVec2 WindowTitleAlign;
    public ImGuiDir WindowMenuButtonPosition;
    public float ChildRounding;
    public float ChildBorderSize;
    public float PopupRounding;
    public float PopupBorderSize;
    public ImVec2 FramePadding;
    public float FrameRounding;
    public float FrameBorderSize;
    public ImVec2 ItemSpacing;
    public ImVec2 ItemInnerSpacing;
    public ImVec2 CellPadding;
    public ImVec2 TouchExtraPadding;
    public float IndentSpacing;
    public float ColumnsMinSpacing;
    public float ScrollbarSize;
    public float ScrollbarRounding;
    public float ScrollbarPadding;
    public float GrabMinSize;
    public float GrabRounding;
    public float LogSliderDeadzone;
    public float ImageRounding;
    public float ImageBorderSize;
    public float TabRounding;
    public float TabBorderSize;
    public float TabMinWidthBase;
    public float TabMinWidthShrink;
    public float TabCloseButtonMinWidthSelected;
    public float TabCloseButtonMinWidthUnselected;
    public float TabBarBorderSize;
    public float TabBarOverlineSize;
    public float TableAngledHeadersAngle;
    public ImVec2 TableAngledHeadersTextAlign;
    public ImGuiTreeNodeFlags_ TreeLinesFlags;
    public float TreeLinesSize;
    public float TreeLinesRounding;
    public float DragDropTargetRounding;
    public float DragDropTargetBorderSize;
    public float DragDropTargetPadding;
    public float ColorMarkerSize;
    public ImGuiDir ColorButtonPosition;
    public ImVec2 ButtonTextAlign;
    public ImVec2 SelectableTextAlign;
    public float SeparatorTextBorderSize;
    public ImVec2 SeparatorTextAlign;
    public ImVec2 SeparatorTextPadding;
    public ImVec2 DisplayWindowPadding;
    public ImVec2 DisplaySafeAreaPadding;
    public float MouseCursorScale;
    public bool AntiAliasedLines;
    public bool AntiAliasedLinesUseTex;
    public bool AntiAliasedFill;
    public float CurveTessellationTol;
    public float CircleTessellationMaxError;
    public float HoverStationaryDelay;
    public float HoverDelayShort;
    public float HoverDelayNormal;
    public ImGuiHoveredFlags_ HoverFlagsForTooltipMouse;
    public ImGuiHoveredFlags_ HoverFlagsForTooltipNav;
    public float _MainScale;
    public float _NextFrameFontSizeBase;

    public ImVec4[] Colors;

    public ImGuiStyle()
    {
        FontSizeBase = 13.0f;
        FontScaleMain = 1.0f;
        FontScaleDpi = 1.0f;

        Alpha = 1.0f;
        DisabledAlpha = 0.60f;
        WindowPadding = new ImVec2(8, 8);
        WindowRounding = 0.0f;
        WindowBorderSize = 1.0f;
        WindowBorderHoverPadding = 4.0f;
        WindowMinSize = new ImVec2(32, 32);
        WindowTitleAlign = new ImVec2(0.0f, 0.5f);
        WindowMenuButtonPosition = ImGuiDir.ImGuiDir_Left;
        ChildRounding = 0.0f;
        ChildBorderSize = 1.0f;
        PopupRounding = 0.0f;
        PopupBorderSize = 1.0f;
        FramePadding = new ImVec2(4, 3);
        FrameRounding = 0.0f;
        FrameBorderSize = 0.0f;
        ItemSpacing = new ImVec2(8, 4);
        ItemInnerSpacing = new ImVec2(4, 4);
        CellPadding = new ImVec2(4, 2);
        TouchExtraPadding = new ImVec2(0, 0);
        IndentSpacing = 21.0f;
        ColumnsMinSpacing = 6.0f;
        ScrollbarSize = 14.0f;
        ScrollbarRounding = 9.0f;
        ScrollbarPadding = 2.0f;
        GrabMinSize = 12.0f;
        GrabRounding = 0.0f;
        LogSliderDeadzone = 4.0f;
        ImageRounding = 0.0f;
        ImageBorderSize = 0.0f;
        TabRounding = 5.0f;
        TabBorderSize = 0.0f;
        TabMinWidthBase = 1.0f;
        TabMinWidthShrink = 80.0f;
        TabCloseButtonMinWidthSelected = -1.0f;
        TabCloseButtonMinWidthUnselected = 0.0f;
        TabBarBorderSize = 1.0f;
        TabBarOverlineSize = 1.0f;
        TableAngledHeadersAngle = 35.0f * ((float)Math.PI / 180.0f);
        TableAngledHeadersTextAlign = new ImVec2(0.5f, 0.0f);
        TreeLinesFlags = ImGuiTreeNodeFlags_.ImGuiTreeNodeFlags_DrawLinesNone;
        TreeLinesSize = 1.0f;
        TreeLinesRounding = 0.0f;
        DragDropTargetRounding = 0.0f;
        DragDropTargetBorderSize = 2.0f;
        DragDropTargetPadding = 3.0f;
        ColorMarkerSize = 3.0f;
        ColorButtonPosition = ImGuiDir.ImGuiDir_Right;
        ButtonTextAlign = new ImVec2(0.5f, 0.5f);
        SelectableTextAlign = new ImVec2(0.0f, 0.0f);
        SeparatorTextBorderSize = 3.0f;
        SeparatorTextAlign = new ImVec2(0.0f, 0.5f);
        SeparatorTextPadding = new ImVec2(20.0f, 3.0f);
        DisplayWindowPadding = new ImVec2(19, 19);
        DisplaySafeAreaPadding = new ImVec2(3, 3);
        MouseCursorScale = 1.0f;
        AntiAliasedLines = true;
        AntiAliasedLinesUseTex = true;
        AntiAliasedFill = true;
        CurveTessellationTol = 1.25f;
        CircleTessellationMaxError = 0.30f;
        HoverStationaryDelay = 0.15f;
        HoverDelayShort = 0.15f;
        HoverDelayNormal = 0.40f;
        HoverFlagsForTooltipMouse = ImGuiHoveredFlags_.ImGuiHoveredFlags_Stationary | ImGuiHoveredFlags_.ImGuiHoveredFlags_DelayShort | ImGuiHoveredFlags_.ImGuiHoveredFlags_AllowWhenDisabled;
        HoverFlagsForTooltipNav = ImGuiHoveredFlags_.ImGuiHoveredFlags_NoSharedDelay | ImGuiHoveredFlags_.ImGuiHoveredFlags_DelayNormal | ImGuiHoveredFlags_.ImGuiHoveredFlags_AllowWhenDisabled;
        _MainScale = 1.0f;
        _NextFrameFontSizeBase = 0.0f;

        Colors = new ImVec4[(int)ImGuiCol_.ImGuiCol_COUNT];
        StyleColorsDark(ref this);
    }

    public void ScaleAllSizes(float scaleFactor)
    {
        _MainScale *= scaleFactor;
        WindowPadding = ImTrunc(WindowPadding * scaleFactor);
        WindowRounding = ImTrunc(WindowRounding * scaleFactor);
        WindowBorderSize = ImTrunc(WindowBorderSize * scaleFactor);
        WindowMinSize = ImTrunc(WindowMinSize * scaleFactor);
        WindowBorderHoverPadding = ImTrunc(WindowBorderHoverPadding * scaleFactor);
        ChildRounding = ImTrunc(ChildRounding * scaleFactor);
        PopupRounding = ImTrunc(PopupRounding * scaleFactor);
        FramePadding = ImTrunc(FramePadding * scaleFactor);
        FrameRounding = ImTrunc(FrameRounding * scaleFactor);
        ItemSpacing = ImTrunc(ItemSpacing * scaleFactor);
        ItemInnerSpacing = ImTrunc(ItemInnerSpacing * scaleFactor);
        CellPadding = ImTrunc(CellPadding * scaleFactor);
        TouchExtraPadding = ImTrunc(TouchExtraPadding * scaleFactor);
        IndentSpacing = ImTrunc(IndentSpacing * scaleFactor);
        ColumnsMinSpacing = ImTrunc(ColumnsMinSpacing * scaleFactor);
        ScrollbarSize = ImTrunc(ScrollbarSize * scaleFactor);
        ScrollbarRounding = ImTrunc(ScrollbarRounding * scaleFactor);
        ScrollbarPadding = ImTrunc(ScrollbarPadding * scaleFactor);
        GrabMinSize = ImTrunc(GrabMinSize * scaleFactor);
        GrabRounding = ImTrunc(GrabRounding * scaleFactor);
        LogSliderDeadzone = ImTrunc(LogSliderDeadzone * scaleFactor);
        ImageRounding = ImTrunc(ImageRounding * scaleFactor);
        ImageBorderSize = ImTrunc(ImageBorderSize * scaleFactor);
        TabRounding = ImTrunc(TabRounding * scaleFactor);
        TabMinWidthBase = ImTrunc(TabMinWidthBase * scaleFactor);
        TabMinWidthShrink = ImTrunc(TabMinWidthShrink * scaleFactor);
        if (TabCloseButtonMinWidthSelected > 0.0f && TabCloseButtonMinWidthSelected != float.MaxValue)
            TabCloseButtonMinWidthSelected = ImTrunc(TabCloseButtonMinWidthSelected * scaleFactor);
        if (TabCloseButtonMinWidthUnselected > 0.0f && TabCloseButtonMinWidthUnselected != float.MaxValue)
            TabCloseButtonMinWidthUnselected = ImTrunc(TabCloseButtonMinWidthUnselected * scaleFactor);
        TabBarOverlineSize = ImTrunc(TabBarOverlineSize * scaleFactor);
        TreeLinesRounding = ImTrunc(TreeLinesRounding * scaleFactor);
        DragDropTargetRounding = ImTrunc(DragDropTargetRounding * scaleFactor);
        DragDropTargetBorderSize = ImTrunc(DragDropTargetBorderSize * scaleFactor);
        DragDropTargetPadding = ImTrunc(DragDropTargetPadding * scaleFactor);
        ColorMarkerSize = ImTrunc(ColorMarkerSize * scaleFactor);
        SeparatorTextPadding = ImTrunc(SeparatorTextPadding * scaleFactor);
        DisplayWindowPadding = ImTrunc(DisplayWindowPadding * scaleFactor);
        DisplaySafeAreaPadding = ImTrunc(DisplaySafeAreaPadding * scaleFactor);
        MouseCursorScale = ImTrunc(MouseCursorScale * scaleFactor);
    }

    public static void StyleColorsDark(ref ImGuiStyle dst)
    {
        var colors = dst.Colors;
        colors[(int)ImGuiCol_.ImGuiCol_Text]                   = new ImVec4(1.00f, 1.00f, 1.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TextDisabled]           = new ImVec4(0.50f, 0.50f, 0.50f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_WindowBg]               = new ImVec4(0.06f, 0.06f, 0.06f, 0.94f);
        colors[(int)ImGuiCol_.ImGuiCol_ChildBg]                = new ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PopupBg]                = new ImVec4(0.08f, 0.08f, 0.08f, 0.94f);
        colors[(int)ImGuiCol_.ImGuiCol_Border]                 = new ImVec4(0.43f, 0.43f, 0.50f, 0.50f);
        colors[(int)ImGuiCol_.ImGuiCol_BorderShadow]           = new ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
        colors[(int)ImGuiCol_.ImGuiCol_FrameBg]                = new ImVec4(0.16f, 0.16f, 0.16f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_FrameBgHovered]         = new ImVec4(0.26f, 0.26f, 0.26f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_FrameBgActive]          = new ImVec4(0.28f, 0.28f, 0.28f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TitleBg]                = new ImVec4(0.04f, 0.04f, 0.04f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TitleBgActive]          = new ImVec4(0.08f, 0.08f, 0.08f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TitleBgCollapsed]       = new ImVec4(0.04f, 0.04f, 0.04f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_MenuBarBg]              = new ImVec4(0.14f, 0.14f, 0.14f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_ScrollbarBg]            = new ImVec4(0.02f, 0.02f, 0.02f, 0.53f);
        colors[(int)ImGuiCol_.ImGuiCol_ScrollbarGrab]          = new ImVec4(0.31f, 0.31f, 0.31f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_ScrollbarGrabHovered]   = new ImVec4(0.41f, 0.41f, 0.41f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_ScrollbarGrabActive]    = new ImVec4(0.51f, 0.51f, 0.51f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_CheckMark]              = new ImVec4(0.26f, 0.59f, 0.98f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_SliderGrab]             = new ImVec4(0.24f, 0.52f, 0.88f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_SliderGrabActive]       = new ImVec4(0.26f, 0.59f, 0.98f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_Button]                 = new ImVec4(0.26f, 0.26f, 0.26f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_ButtonHovered]          = new ImVec4(0.30f, 0.30f, 0.30f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_ButtonActive]           = new ImVec4(0.20f, 0.22f, 0.23f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_Header]                 = new ImVec4(0.20f, 0.20f, 0.20f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_HeaderHovered]          = new ImVec4(0.30f, 0.30f, 0.30f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_HeaderActive]           = new ImVec4(0.20f, 0.22f, 0.23f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_Separator]              = new ImVec4(0.43f, 0.43f, 0.50f, 0.50f);
        colors[(int)ImGuiCol_.ImGuiCol_SeparatorHovered]       = new ImVec4(0.52f, 0.52f, 0.52f, 0.50f);
        colors[(int)ImGuiCol_.ImGuiCol_SeparatorActive]        = new ImVec4(0.41f, 0.41f, 0.41f, 0.50f);
        colors[(int)ImGuiCol_.ImGuiCol_ResizeGrip]             = new ImVec4(0.26f, 0.59f, 0.98f, 0.25f);
        colors[(int)ImGuiCol_.ImGuiCol_ResizeGripHovered]      = new ImVec4(0.26f, 0.59f, 0.98f, 0.67f);
        colors[(int)ImGuiCol_.ImGuiCol_ResizeGripActive]       = new ImVec4(0.26f, 0.59f, 0.98f, 0.95f);
        colors[(int)ImGuiCol_.ImGuiCol_InputTextCursor]        = new ImVec4(1.00f, 1.00f, 1.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TabHovered]             = new ImVec4(0.26f, 0.59f, 0.98f, 0.80f);
        colors[(int)ImGuiCol_.ImGuiCol_Tab]                    = new ImVec4(0.11f, 0.15f, 0.17f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TabSelected]            = new ImVec4(0.16f, 0.28f, 0.36f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TabSelectedOverline]    = new ImVec4(0.26f, 0.59f, 0.98f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TabDimmed]              = new ImVec4(0.11f, 0.15f, 0.17f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TabDimmedSelected]      = new ImVec4(0.16f, 0.26f, 0.32f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TabDimmedSelectedOverline] = new ImVec4(0.26f, 0.59f, 0.98f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PlotLines]              = new ImVec4(0.61f, 0.61f, 0.61f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PlotLinesHovered]       = new ImVec4(1.00f, 0.43f, 0.35f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PlotHistogram]          = new ImVec4(0.90f, 0.70f, 0.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PlotHistogramHovered]   = new ImVec4(1.00f, 0.60f, 0.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableHeaderBg]          = new ImVec4(0.19f, 0.19f, 0.20f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableBorderStrong]      = new ImVec4(0.31f, 0.31f, 0.35f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableBorderLight]       = new ImVec4(0.23f, 0.23f, 0.25f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableRowBg]             = new ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableRowBgAlt]          = new ImVec4(0.18f, 0.18f, 0.18f, 0.06f);
        colors[(int)ImGuiCol_.ImGuiCol_TextLink]               = new ImVec4(0.26f, 0.59f, 0.98f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TextSelectedBg]         = new ImVec4(0.26f, 0.59f, 0.98f, 0.35f);
        colors[(int)ImGuiCol_.ImGuiCol_TreeLines]              = new ImVec4(0.19f, 0.19f, 0.20f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_DragDropTarget]         = new ImVec4(1.00f, 1.00f, 0.00f, 0.90f);
        colors[(int)ImGuiCol_.ImGuiCol_DragDropTargetBg]       = new ImVec4(0.90f, 0.90f, 0.20f, 0.40f);
        colors[(int)ImGuiCol_.ImGuiCol_UnsavedMarker]          = new ImVec4(1.00f, 0.40f, 0.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_NavCursor]              = new ImVec4(1.00f, 1.00f, 0.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_NavWindowingHighlight]  = new ImVec4(1.00f, 1.00f, 1.00f, 0.70f);
        colors[(int)ImGuiCol_.ImGuiCol_NavWindowingDimBg]      = new ImVec4(0.80f, 0.80f, 0.80f, 0.20f);
        colors[(int)ImGuiCol_.ImGuiCol_ModalWindowDimBg]       = new ImVec4(0.80f, 0.80f, 0.80f, 0.35f);
    }

    public static void StyleColorsClassic(ref ImGuiStyle dst)
    {
        var colors = dst.Colors;
        colors[(int)ImGuiCol_.ImGuiCol_Text]                   = new ImVec4(0.90f, 0.90f, 0.90f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TextDisabled]           = new ImVec4(0.60f, 0.60f, 0.60f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_WindowBg]               = new ImVec4(0.00f, 0.00f, 0.00f, 0.85f);
        colors[(int)ImGuiCol_.ImGuiCol_ChildBg]                = new ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PopupBg]                = new ImVec4(0.11f, 0.11f, 0.14f, 0.92f);
        colors[(int)ImGuiCol_.ImGuiCol_Border]                 = new ImVec4(0.50f, 0.50f, 0.50f, 0.50f);
        colors[(int)ImGuiCol_.ImGuiCol_BorderShadow]           = new ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
        colors[(int)ImGuiCol_.ImGuiCol_FrameBg]                = new ImVec4(0.43f, 0.43f, 0.43f, 0.39f);
        colors[(int)ImGuiCol_.ImGuiCol_FrameBgHovered]         = new ImVec4(0.47f, 0.47f, 0.69f, 0.40f);
        colors[(int)ImGuiCol_.ImGuiCol_FrameBgActive]          = new ImVec4(0.42f, 0.41f, 0.64f, 0.69f);
        colors[(int)ImGuiCol_.ImGuiCol_TitleBg]                = new ImVec4(0.27f, 0.27f, 0.54f, 0.83f);
        colors[(int)ImGuiCol_.ImGuiCol_TitleBgActive]          = new ImVec4(0.32f, 0.32f, 0.63f, 0.87f);
        colors[(int)ImGuiCol_.ImGuiCol_TitleBgCollapsed]       = new ImVec4(0.40f, 0.40f, 0.80f, 0.20f);
        colors[(int)ImGuiCol_.ImGuiCol_MenuBarBg]              = new ImVec4(0.40f, 0.40f, 0.55f, 0.80f);
        colors[(int)ImGuiCol_.ImGuiCol_ScrollbarBg]            = new ImVec4(0.20f, 0.25f, 0.30f, 0.60f);
        colors[(int)ImGuiCol_.ImGuiCol_ScrollbarGrab]          = new ImVec4(0.40f, 0.40f, 0.80f, 0.30f);
        colors[(int)ImGuiCol_.ImGuiCol_ScrollbarGrabHovered]   = new ImVec4(0.40f, 0.40f, 0.80f, 0.40f);
        colors[(int)ImGuiCol_.ImGuiCol_ScrollbarGrabActive]    = new ImVec4(0.41f, 0.39f, 0.80f, 0.60f);
        colors[(int)ImGuiCol_.ImGuiCol_CheckMark]              = new ImVec4(0.90f, 0.90f, 0.90f, 0.50f);
        colors[(int)ImGuiCol_.ImGuiCol_SliderGrab]             = new ImVec4(1.00f, 1.00f, 1.00f, 0.30f);
        colors[(int)ImGuiCol_.ImGuiCol_SliderGrabActive]       = new ImVec4(0.41f, 0.39f, 0.80f, 0.60f);
        colors[(int)ImGuiCol_.ImGuiCol_Button]                 = new ImVec4(0.35f, 0.40f, 0.61f, 0.62f);
        colors[(int)ImGuiCol_.ImGuiCol_ButtonHovered]          = new ImVec4(0.40f, 0.48f, 0.71f, 0.79f);
        colors[(int)ImGuiCol_.ImGuiCol_ButtonActive]           = new ImVec4(0.46f, 0.54f, 0.80f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_Header]                 = new ImVec4(0.40f, 0.40f, 0.90f, 0.45f);
        colors[(int)ImGuiCol_.ImGuiCol_HeaderHovered]          = new ImVec4(0.45f, 0.45f, 0.90f, 0.80f);
        colors[(int)ImGuiCol_.ImGuiCol_HeaderActive]           = new ImVec4(0.53f, 0.53f, 0.87f, 0.80f);
        colors[(int)ImGuiCol_.ImGuiCol_Separator]              = new ImVec4(0.50f, 0.50f, 0.50f, 0.60f);
        colors[(int)ImGuiCol_.ImGuiCol_SeparatorHovered]       = new ImVec4(0.60f, 0.60f, 0.70f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_SeparatorActive]        = new ImVec4(0.70f, 0.70f, 0.90f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_ResizeGrip]             = new ImVec4(1.00f, 1.00f, 1.00f, 0.10f);
        colors[(int)ImGuiCol_.ImGuiCol_ResizeGripHovered]      = new ImVec4(0.78f, 0.82f, 1.00f, 0.60f);
        colors[(int)ImGuiCol_.ImGuiCol_ResizeGripActive]       = new ImVec4(0.78f, 0.82f, 1.00f, 0.90f);
        colors[(int)ImGuiCol_.ImGuiCol_InputTextCursor]        = colors[(int)ImGuiCol_.ImGuiCol_Text];
        colors[(int)ImGuiCol_.ImGuiCol_TabHovered]             = colors[(int)ImGuiCol_.ImGuiCol_HeaderHovered];
        colors[(int)ImGuiCol_.ImGuiCol_Tab]                    = Lerp(colors[(int)ImGuiCol_.ImGuiCol_Header], colors[(int)ImGuiCol_.ImGuiCol_TitleBgActive], 0.80f);
        colors[(int)ImGuiCol_.ImGuiCol_TabSelected]            = Lerp(colors[(int)ImGuiCol_.ImGuiCol_HeaderActive], colors[(int)ImGuiCol_.ImGuiCol_TitleBgActive], 0.60f);
        colors[(int)ImGuiCol_.ImGuiCol_TabSelectedOverline]    = colors[(int)ImGuiCol_.ImGuiCol_HeaderActive];
        colors[(int)ImGuiCol_.ImGuiCol_TabDimmed]              = Lerp(colors[(int)ImGuiCol_.ImGuiCol_Tab], colors[(int)ImGuiCol_.ImGuiCol_TitleBg], 0.80f);
        colors[(int)ImGuiCol_.ImGuiCol_TabDimmedSelected]      = Lerp(colors[(int)ImGuiCol_.ImGuiCol_TabSelected], colors[(int)ImGuiCol_.ImGuiCol_TitleBg], 0.40f);
        colors[(int)ImGuiCol_.ImGuiCol_TabDimmedSelectedOverline] = new ImVec4(0.53f, 0.53f, 0.87f, 0.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PlotLines]              = new ImVec4(1.00f, 1.00f, 1.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PlotLinesHovered]       = new ImVec4(0.90f, 0.70f, 0.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PlotHistogram]          = new ImVec4(0.90f, 0.70f, 0.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PlotHistogramHovered]   = new ImVec4(1.00f, 0.60f, 0.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableHeaderBg]          = new ImVec4(0.27f, 0.27f, 0.38f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableBorderStrong]      = new ImVec4(0.31f, 0.31f, 0.45f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableBorderLight]       = new ImVec4(0.26f, 0.26f, 0.28f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableRowBg]             = new ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableRowBgAlt]          = new ImVec4(1.00f, 1.00f, 1.00f, 0.07f);
        colors[(int)ImGuiCol_.ImGuiCol_TextLink]               = colors[(int)ImGuiCol_.ImGuiCol_HeaderActive];
        colors[(int)ImGuiCol_.ImGuiCol_TextSelectedBg]         = new ImVec4(0.00f, 0.00f, 1.00f, 0.35f);
        colors[(int)ImGuiCol_.ImGuiCol_TreeLines]              = colors[(int)ImGuiCol_.ImGuiCol_Border];
        colors[(int)ImGuiCol_.ImGuiCol_DragDropTarget]         = new ImVec4(1.00f, 1.00f, 0.00f, 0.90f);
        colors[(int)ImGuiCol_.ImGuiCol_DragDropTargetBg]       = new ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
        colors[(int)ImGuiCol_.ImGuiCol_UnsavedMarker]          = new ImVec4(0.90f, 0.90f, 0.90f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_NavCursor]              = colors[(int)ImGuiCol_.ImGuiCol_HeaderHovered];
        colors[(int)ImGuiCol_.ImGuiCol_NavWindowingHighlight]  = new ImVec4(1.00f, 1.00f, 1.00f, 0.70f);
        colors[(int)ImGuiCol_.ImGuiCol_NavWindowingDimBg]      = new ImVec4(0.80f, 0.80f, 0.80f, 0.20f);
        colors[(int)ImGuiCol_.ImGuiCol_ModalWindowDimBg]       = new ImVec4(0.20f, 0.20f, 0.20f, 0.35f);
    }

    public static void StyleColorsLight(ref ImGuiStyle dst)
    {
        var colors = dst.Colors;
        colors[(int)ImGuiCol_.ImGuiCol_Text]                   = new ImVec4(0.00f, 0.00f, 0.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TextDisabled]           = new ImVec4(0.60f, 0.60f, 0.60f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_WindowBg]               = new ImVec4(0.94f, 0.94f, 0.94f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_ChildBg]                = new ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PopupBg]                = new ImVec4(1.00f, 1.00f, 1.00f, 0.98f);
        colors[(int)ImGuiCol_.ImGuiCol_Border]                 = new ImVec4(0.00f, 0.00f, 0.00f, 0.30f);
        colors[(int)ImGuiCol_.ImGuiCol_BorderShadow]           = new ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
        colors[(int)ImGuiCol_.ImGuiCol_FrameBg]                = new ImVec4(1.00f, 1.00f, 1.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_FrameBgHovered]         = new ImVec4(0.26f, 0.59f, 0.98f, 0.40f);
        colors[(int)ImGuiCol_.ImGuiCol_FrameBgActive]          = new ImVec4(0.26f, 0.59f, 0.98f, 0.67f);
        colors[(int)ImGuiCol_.ImGuiCol_TitleBg]                = new ImVec4(0.96f, 0.96f, 0.96f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TitleBgActive]          = new ImVec4(0.82f, 0.82f, 0.82f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TitleBgCollapsed]       = new ImVec4(1.00f, 1.00f, 1.00f, 0.51f);
        colors[(int)ImGuiCol_.ImGuiCol_MenuBarBg]              = new ImVec4(0.86f, 0.86f, 0.86f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_ScrollbarBg]            = new ImVec4(0.98f, 0.98f, 0.98f, 0.53f);
        colors[(int)ImGuiCol_.ImGuiCol_ScrollbarGrab]          = new ImVec4(0.69f, 0.69f, 0.69f, 0.80f);
        colors[(int)ImGuiCol_.ImGuiCol_ScrollbarGrabHovered]   = new ImVec4(0.49f, 0.49f, 0.49f, 0.80f);
        colors[(int)ImGuiCol_.ImGuiCol_ScrollbarGrabActive]    = new ImVec4(0.49f, 0.49f, 0.49f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_CheckMark]              = new ImVec4(0.26f, 0.59f, 0.98f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_SliderGrab]             = new ImVec4(0.26f, 0.59f, 0.98f, 0.78f);
        colors[(int)ImGuiCol_.ImGuiCol_SliderGrabActive]       = new ImVec4(0.46f, 0.54f, 0.80f, 0.60f);
        colors[(int)ImGuiCol_.ImGuiCol_Button]                 = new ImVec4(0.26f, 0.59f, 0.98f, 0.40f);
        colors[(int)ImGuiCol_.ImGuiCol_ButtonHovered]          = new ImVec4(0.26f, 0.59f, 0.98f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_ButtonActive]           = new ImVec4(0.06f, 0.53f, 0.98f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_Header]                 = new ImVec4(0.26f, 0.59f, 0.98f, 0.31f);
        colors[(int)ImGuiCol_.ImGuiCol_HeaderHovered]          = new ImVec4(0.26f, 0.59f, 0.98f, 0.80f);
        colors[(int)ImGuiCol_.ImGuiCol_HeaderActive]           = new ImVec4(0.26f, 0.59f, 0.98f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_Separator]              = new ImVec4(0.39f, 0.39f, 0.39f, 0.62f);
        colors[(int)ImGuiCol_.ImGuiCol_SeparatorHovered]       = new ImVec4(0.14f, 0.44f, 0.80f, 0.78f);
        colors[(int)ImGuiCol_.ImGuiCol_SeparatorActive]        = new ImVec4(0.14f, 0.44f, 0.80f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_ResizeGrip]             = new ImVec4(0.35f, 0.35f, 0.35f, 0.17f);
        colors[(int)ImGuiCol_.ImGuiCol_ResizeGripHovered]      = new ImVec4(0.26f, 0.59f, 0.98f, 0.67f);
        colors[(int)ImGuiCol_.ImGuiCol_ResizeGripActive]       = new ImVec4(0.26f, 0.59f, 0.98f, 0.95f);
        colors[(int)ImGuiCol_.ImGuiCol_InputTextCursor]        = colors[(int)ImGuiCol_.ImGuiCol_Text];
        colors[(int)ImGuiCol_.ImGuiCol_TabHovered]             = colors[(int)ImGuiCol_.ImGuiCol_HeaderHovered];
        colors[(int)ImGuiCol_.ImGuiCol_Tab]                    = Lerp(colors[(int)ImGuiCol_.ImGuiCol_Header], colors[(int)ImGuiCol_.ImGuiCol_TitleBgActive], 0.90f);
        colors[(int)ImGuiCol_.ImGuiCol_TabSelected]            = Lerp(colors[(int)ImGuiCol_.ImGuiCol_HeaderActive], colors[(int)ImGuiCol_.ImGuiCol_TitleBgActive], 0.60f);
        colors[(int)ImGuiCol_.ImGuiCol_TabSelectedOverline]    = colors[(int)ImGuiCol_.ImGuiCol_HeaderActive];
        colors[(int)ImGuiCol_.ImGuiCol_TabDimmed]              = Lerp(colors[(int)ImGuiCol_.ImGuiCol_Tab], colors[(int)ImGuiCol_.ImGuiCol_TitleBg], 0.80f);
        colors[(int)ImGuiCol_.ImGuiCol_TabDimmedSelected]      = Lerp(colors[(int)ImGuiCol_.ImGuiCol_TabSelected], colors[(int)ImGuiCol_.ImGuiCol_TitleBg], 0.40f);
        colors[(int)ImGuiCol_.ImGuiCol_TabDimmedSelectedOverline] = new ImVec4(0.26f, 0.59f, 1.00f, 0.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PlotLines]              = new ImVec4(0.39f, 0.39f, 0.39f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PlotLinesHovered]       = new ImVec4(1.00f, 0.43f, 0.35f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PlotHistogram]          = new ImVec4(0.90f, 0.70f, 0.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_PlotHistogramHovered]   = new ImVec4(1.00f, 0.45f, 0.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableHeaderBg]          = new ImVec4(0.78f, 0.87f, 0.98f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableBorderStrong]      = new ImVec4(0.57f, 0.57f, 0.64f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableBorderLight]       = new ImVec4(0.68f, 0.68f, 0.74f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableRowBg]             = new ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
        colors[(int)ImGuiCol_.ImGuiCol_TableRowBgAlt]          = new ImVec4(0.30f, 0.30f, 0.30f, 0.09f);
        colors[(int)ImGuiCol_.ImGuiCol_TextLink]               = colors[(int)ImGuiCol_.ImGuiCol_HeaderActive];
        colors[(int)ImGuiCol_.ImGuiCol_TextSelectedBg]         = new ImVec4(0.26f, 0.59f, 0.98f, 0.35f);
        colors[(int)ImGuiCol_.ImGuiCol_TreeLines]              = colors[(int)ImGuiCol_.ImGuiCol_Border];
        colors[(int)ImGuiCol_.ImGuiCol_DragDropTarget]         = new ImVec4(0.26f, 0.59f, 0.98f, 0.95f);
        colors[(int)ImGuiCol_.ImGuiCol_DragDropTargetBg]       = new ImVec4(0.00f, 0.00f, 0.00f, 0.00f);
        colors[(int)ImGuiCol_.ImGuiCol_UnsavedMarker]          = new ImVec4(0.00f, 0.00f, 0.00f, 1.00f);
        colors[(int)ImGuiCol_.ImGuiCol_NavCursor]              = colors[(int)ImGuiCol_.ImGuiCol_HeaderHovered];
        colors[(int)ImGuiCol_.ImGuiCol_NavWindowingHighlight]  = new ImVec4(0.70f, 0.70f, 0.70f, 0.70f);
        colors[(int)ImGuiCol_.ImGuiCol_NavWindowingDimBg]      = new ImVec4(0.20f, 0.20f, 0.20f, 0.20f);
        colors[(int)ImGuiCol_.ImGuiCol_ModalWindowDimBg]       = new ImVec4(0.20f, 0.20f, 0.20f, 0.35f);
    }

    private static ImVec4 Lerp(ImVec4 a, ImVec4 b, float t)
    {
        return new ImVec4(
            a.x + (b.x - a.x) * t,
            a.y + (b.y - a.y) * t,
            a.z + (b.z - a.z) * t,
            a.w + (b.w - a.w) * t);
    }

    private static float ImTrunc(float v) => (float)Math.Floor(v);
    private static ImVec2 ImTrunc(ImVec2 v) => new(ImTrunc(v.x), ImTrunc(v.y));
}
